### ISSUE TITLE
name 'model' is not defined

### ISSUE THREAD

**Issue by Georgendragon** [hidude562/OpenMusenet2#1]
Hi, I'm new to GitHub and Google Colab, and have come across an issue which I have no idea how to fix. When running the generation cell in Colab it stops halfway with this problem
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-13-e0f3129135d4>](https://5l92wogfrd-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230817-060103-RC00_557775453#) in <cell line: 3>()
      1 #@title Generate
      2 device = torch.device("cuda")
----> 3 model.cuda()
      4 
      5 #generated = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)

NameError: name 'model' is not defined
---------------------------------------------------------------------------
Any ideas on what I'm doing wrong? Thanks

**Comment by hidude562** [comment]
If you restarted the runtime, make sure you re-ran all the previous cells. Also do make sure you've ran all the previous cells. Hopefully helps if you haven't fixed it yet or if someone else is reading this from the future.
